/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My School APIs
 * My School API documentation
 * OpenAPI spec version: 1.0
 */

export interface CreateStudentDto {
  name: string;
  age: number;
  birthDate?: string;
  gender: string;
  classId: string;
  sectionId: string;
  admissionDate: string;
  rollNo: number;
  fatherName?: string;
  motherName?: string;
  phone?: string;
  email?: string;
  address?: string;
  isActive: boolean;
}
