/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My School APIs
 * My School API documentation
 * OpenAPI spec version: 1.0
 */
import type { ResponseSectionDto } from './responseSectionDto';
import type { MetadataDto } from './metadataDto';

export interface FindAllSectionResponseDto {
  data: ResponseSectionDto[];
  metadata: MetadataDto;
  message: string;
  status: number;
}
