/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My School APIs
 * My School API documentation
 * OpenAPI spec version: 1.0
 */
import type { ResponseSectionDto } from './responseSectionDto';

export interface FindOneSectionResponseDto {
  data: ResponseSectionDto;
  message: string;
  status: number;
}
