/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My School APIs
 * My School API documentation
 * OpenAPI spec version: 1.0
 */

export * from "./createAcademixDto";
export * from "./createSectionDto";
export * from "./createStudentDto";
export * from "./findAllSectionResponseDto";
export * from "./findAllSectionResponseDtoMetadata";
export * from "./findOneSectionResponseDto";
export * from "./messageDto";
export * from "./metadataDto";
export * from "./responseAcademixDto";
export * from "./responseSectionDto";
export * from "./updateAcademixDto";
export * from "./updateSectionDto";
export * from "./updateStudentDto";