/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My School APIs
 * My School API documentation
 * OpenAPI spec version: 1.0
 */
import type { MetadataDto } from './metadataDto';
import type { LoginResponseData } from './loginResponseData';

export interface LoginResponseDto {
  message: string;
  status: number;
  metadata?: MetadataDto;
  data: LoginResponseData;
  access_token: string;
}
