/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My School APIs
 * My School API documentation
 * OpenAPI spec version: 1.0
 */

export interface ResponseSectionDto {
  id: string;
  name: string;
  isActive: boolean;
}
