/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My School APIs
 * My School API documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateAcademixDto,
  ResponseAcademixDto,
  UpdateAcademixDto
} from '../../models';

import { axiosInstance } from '../../axios';




/**
 * @summary Generate response from academix
 */
export const academixControllerGenerate = (
    createAcademixDto: CreateAcademixDto,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ResponseAcademixDto>(
      {url: `http://localhost:3001/academix/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAcademixDto, signal
    },
      );
    }
  


export const getAcademixControllerGenerateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof academixControllerGenerate>>, TError,{data: CreateAcademixDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof academixControllerGenerate>>, TError,{data: CreateAcademixDto}, TContext> => {

const mutationKey = ['academixControllerGenerate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof academixControllerGenerate>>, {data: CreateAcademixDto}> = (props) => {
          const {data} = props ?? {};

          return  academixControllerGenerate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AcademixControllerGenerateMutationResult = NonNullable<Awaited<ReturnType<typeof academixControllerGenerate>>>
    export type AcademixControllerGenerateMutationBody = CreateAcademixDto
    export type AcademixControllerGenerateMutationError = unknown

    /**
 * @summary Generate response from academix
 */
export const useAcademixControllerGenerate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof academixControllerGenerate>>, TError,{data: CreateAcademixDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof academixControllerGenerate>>,
        TError,
        {data: CreateAcademixDto},
        TContext
      > => {

      const mutationOptions = getAcademixControllerGenerateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const academixControllerCreate = (
    createAcademixDto: CreateAcademixDto,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/academix`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAcademixDto, signal
    },
      );
    }
  


export const getAcademixControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof academixControllerCreate>>, TError,{data: CreateAcademixDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof academixControllerCreate>>, TError,{data: CreateAcademixDto}, TContext> => {

const mutationKey = ['academixControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof academixControllerCreate>>, {data: CreateAcademixDto}> = (props) => {
          const {data} = props ?? {};

          return  academixControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AcademixControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof academixControllerCreate>>>
    export type AcademixControllerCreateMutationBody = CreateAcademixDto
    export type AcademixControllerCreateMutationError = unknown

    export const useAcademixControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof academixControllerCreate>>, TError,{data: CreateAcademixDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof academixControllerCreate>>,
        TError,
        {data: CreateAcademixDto},
        TContext
      > => {

      const mutationOptions = getAcademixControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const academixControllerFindOne = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/academix/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getAcademixControllerFindOneQueryKey = (id?: string,) => {
    return [
    `http://localhost:3001/academix/${id}`
    ] as const;
    }

    
export const getAcademixControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof academixControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof academixControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAcademixControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof academixControllerFindOne>>> = ({ signal }) => academixControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof academixControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AcademixControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof academixControllerFindOne>>>
export type AcademixControllerFindOneQueryError = unknown


export function useAcademixControllerFindOne<TData = Awaited<ReturnType<typeof academixControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof academixControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof academixControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof academixControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAcademixControllerFindOne<TData = Awaited<ReturnType<typeof academixControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof academixControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof academixControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof academixControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAcademixControllerFindOne<TData = Awaited<ReturnType<typeof academixControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof academixControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAcademixControllerFindOne<TData = Awaited<ReturnType<typeof academixControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof academixControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAcademixControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const academixControllerUpdate = (
    id: string,
    updateAcademixDto: UpdateAcademixDto,
 ) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/academix/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateAcademixDto
    },
      );
    }
  


export const getAcademixControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof academixControllerUpdate>>, TError,{id: string;data: UpdateAcademixDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof academixControllerUpdate>>, TError,{id: string;data: UpdateAcademixDto}, TContext> => {

const mutationKey = ['academixControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof academixControllerUpdate>>, {id: string;data: UpdateAcademixDto}> = (props) => {
          const {id,data} = props ?? {};

          return  academixControllerUpdate(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AcademixControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof academixControllerUpdate>>>
    export type AcademixControllerUpdateMutationBody = UpdateAcademixDto
    export type AcademixControllerUpdateMutationError = unknown

    export const useAcademixControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof academixControllerUpdate>>, TError,{id: string;data: UpdateAcademixDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof academixControllerUpdate>>,
        TError,
        {id: string;data: UpdateAcademixDto},
        TContext
      > => {

      const mutationOptions = getAcademixControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const academixControllerRemove = (
    id: string,
 ) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/academix/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getAcademixControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof academixControllerRemove>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof academixControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['academixControllerRemove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof academixControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  academixControllerRemove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AcademixControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof academixControllerRemove>>>
    
    export type AcademixControllerRemoveMutationError = unknown

    export const useAcademixControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof academixControllerRemove>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof academixControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getAcademixControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    