/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My School APIs
 * My School API documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateStudentDto,
  UpdateStudentDto
} from '../../models';

import { axiosInstance } from '../../axios';




/**
 * @summary Create a new student
 */
export const studentsControllerCreate = (
    createStudentDto: CreateStudentDto,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/students`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStudentDto, signal
    },
      );
    }
  


export const getStudentsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studentsControllerCreate>>, TError,{data: CreateStudentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof studentsControllerCreate>>, TError,{data: CreateStudentDto}, TContext> => {

const mutationKey = ['studentsControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof studentsControllerCreate>>, {data: CreateStudentDto}> = (props) => {
          const {data} = props ?? {};

          return  studentsControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StudentsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof studentsControllerCreate>>>
    export type StudentsControllerCreateMutationBody = CreateStudentDto
    export type StudentsControllerCreateMutationError = void

    /**
 * @summary Create a new student
 */
export const useStudentsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studentsControllerCreate>>, TError,{data: CreateStudentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof studentsControllerCreate>>,
        TError,
        {data: CreateStudentDto},
        TContext
      > => {

      const mutationOptions = getStudentsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all students
 */
export const studentsControllerFindAll = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/students`, method: 'GET', signal
    },
      );
    }
  



export const getStudentsControllerFindAllQueryKey = () => {
    return [
    `http://localhost:3001/students`
    ] as const;
    }

    
export const getStudentsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof studentsControllerFindAll>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStudentsControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof studentsControllerFindAll>>> = ({ signal }) => studentsControllerFindAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StudentsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof studentsControllerFindAll>>>
export type StudentsControllerFindAllQueryError = void


export function useStudentsControllerFindAll<TData = Awaited<ReturnType<typeof studentsControllerFindAll>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof studentsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof studentsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStudentsControllerFindAll<TData = Awaited<ReturnType<typeof studentsControllerFindAll>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof studentsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof studentsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStudentsControllerFindAll<TData = Awaited<ReturnType<typeof studentsControllerFindAll>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all students
 */

export function useStudentsControllerFindAll<TData = Awaited<ReturnType<typeof studentsControllerFindAll>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStudentsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get a student by ID
 */
export const studentsControllerFindOne = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/students/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getStudentsControllerFindOneQueryKey = (id?: string,) => {
    return [
    `http://localhost:3001/students/${id}`
    ] as const;
    }

    
export const getStudentsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof studentsControllerFindOne>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStudentsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof studentsControllerFindOne>>> = ({ signal }) => studentsControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StudentsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof studentsControllerFindOne>>>
export type StudentsControllerFindOneQueryError = void


export function useStudentsControllerFindOne<TData = Awaited<ReturnType<typeof studentsControllerFindOne>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof studentsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof studentsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStudentsControllerFindOne<TData = Awaited<ReturnType<typeof studentsControllerFindOne>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof studentsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof studentsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStudentsControllerFindOne<TData = Awaited<ReturnType<typeof studentsControllerFindOne>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a student by ID
 */

export function useStudentsControllerFindOne<TData = Awaited<ReturnType<typeof studentsControllerFindOne>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof studentsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStudentsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update a student by ID
 */
export const studentsControllerUpdate = (
    id: string,
    updateStudentDto: UpdateStudentDto,
 ) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/students/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateStudentDto
    },
      );
    }
  


export const getStudentsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studentsControllerUpdate>>, TError,{id: string;data: UpdateStudentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof studentsControllerUpdate>>, TError,{id: string;data: UpdateStudentDto}, TContext> => {

const mutationKey = ['studentsControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof studentsControllerUpdate>>, {id: string;data: UpdateStudentDto}> = (props) => {
          const {id,data} = props ?? {};

          return  studentsControllerUpdate(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StudentsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof studentsControllerUpdate>>>
    export type StudentsControllerUpdateMutationBody = UpdateStudentDto
    export type StudentsControllerUpdateMutationError = void

    /**
 * @summary Update a student by ID
 */
export const useStudentsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studentsControllerUpdate>>, TError,{id: string;data: UpdateStudentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof studentsControllerUpdate>>,
        TError,
        {id: string;data: UpdateStudentDto},
        TContext
      > => {

      const mutationOptions = getStudentsControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a student by ID
 */
export const studentsControllerRemove = (
    id: string,
 ) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/students/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getStudentsControllerRemoveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studentsControllerRemove>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof studentsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['studentsControllerRemove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof studentsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  studentsControllerRemove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StudentsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof studentsControllerRemove>>>
    
    export type StudentsControllerRemoveMutationError = void

    /**
 * @summary Delete a student by ID
 */
export const useStudentsControllerRemove = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studentsControllerRemove>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof studentsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getStudentsControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    