/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My School APIs
 * My School API documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSectionDto,
  FindAllSectionResponseDto,
  FindOneSectionResponseDto,
  UpdateSectionDto
} from '../../models';

import { axiosInstance } from '../../axios';




/**
 * @summary Create a new section
 */
export const sectionsControllerCreate = (
    createSectionDto: CreateSectionDto,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/sections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSectionDto, signal
    },
      );
    }
  


export const getSectionsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerCreate>>, TError,{data: CreateSectionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerCreate>>, TError,{data: CreateSectionDto}, TContext> => {

const mutationKey = ['sectionsControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sectionsControllerCreate>>, {data: CreateSectionDto}> = (props) => {
          const {data} = props ?? {};

          return  sectionsControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SectionsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerCreate>>>
    export type SectionsControllerCreateMutationBody = CreateSectionDto
    export type SectionsControllerCreateMutationError = void

    /**
 * @summary Create a new section
 */
export const useSectionsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerCreate>>, TError,{data: CreateSectionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sectionsControllerCreate>>,
        TError,
        {data: CreateSectionDto},
        TContext
      > => {

      const mutationOptions = getSectionsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all sections
 */
export const sectionsControllerFindAll = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<FindAllSectionResponseDto>(
      {url: `http://localhost:3001/sections`, method: 'GET', signal
    },
      );
    }
  



export const getSectionsControllerFindAllQueryKey = () => {
    return [
    `http://localhost:3001/sections`
    ] as const;
    }

    
export const getSectionsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSectionsControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sectionsControllerFindAll>>> = ({ signal }) => sectionsControllerFindAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SectionsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerFindAll>>>
export type SectionsControllerFindAllQueryError = unknown


export function useSectionsControllerFindAll<TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectionsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sectionsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectionsControllerFindAll<TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectionsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sectionsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectionsControllerFindAll<TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all sections
 */

export function useSectionsControllerFindAll<TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSectionsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all sections
 */
export const sectionsControllerFindOne = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<FindOneSectionResponseDto>(
      {url: `http://localhost:3001/sections/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getSectionsControllerFindOneQueryKey = (id?: string,) => {
    return [
    `http://localhost:3001/sections/${id}`
    ] as const;
    }

    
export const getSectionsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSectionsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sectionsControllerFindOne>>> = ({ signal }) => sectionsControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SectionsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerFindOne>>>
export type SectionsControllerFindOneQueryError = unknown


export function useSectionsControllerFindOne<TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectionsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sectionsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectionsControllerFindOne<TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectionsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sectionsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectionsControllerFindOne<TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all sections
 */

export function useSectionsControllerFindOne<TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSectionsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update a section by ID
 */
export const sectionsControllerUpdate = (
    id: string,
    updateSectionDto: UpdateSectionDto,
 ) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/sections/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSectionDto
    },
      );
    }
  


export const getSectionsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerUpdate>>, TError,{id: string;data: UpdateSectionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerUpdate>>, TError,{id: string;data: UpdateSectionDto}, TContext> => {

const mutationKey = ['sectionsControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sectionsControllerUpdate>>, {id: string;data: UpdateSectionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  sectionsControllerUpdate(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SectionsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerUpdate>>>
    export type SectionsControllerUpdateMutationBody = UpdateSectionDto
    export type SectionsControllerUpdateMutationError = void

    /**
 * @summary Update a section by ID
 */
export const useSectionsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerUpdate>>, TError,{id: string;data: UpdateSectionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sectionsControllerUpdate>>,
        TError,
        {id: string;data: UpdateSectionDto},
        TContext
      > => {

      const mutationOptions = getSectionsControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a section by ID
 */
export const sectionsControllerRemove = (
    id: string,
 ) => {
      
      
      return axiosInstance<void>(
      {url: `http://localhost:3001/sections/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getSectionsControllerRemoveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerRemove>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['sectionsControllerRemove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sectionsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  sectionsControllerRemove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SectionsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerRemove>>>
    
    export type SectionsControllerRemoveMutationError = void

    /**
 * @summary Delete a section by ID
 */
export const useSectionsControllerRemove = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerRemove>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sectionsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getSectionsControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    